version: "3"
services:
  mongodb-database:
    image: mongo:latest
    container_name: mongo-food
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
